name: CI - Selenium & Cypress with Allure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # -------------------
      # 1) Ejecutar Selenium
      # -------------------
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Selenium Tests (Maven)
        working-directory: Selenium/selenium-fotocasa-tests
        run: mvn clean test

      - name: Copy Selenium Allure results
        run: |
          mkdir -p joint-allure-results
          cp -r Selenium/selenium-fotocasa-tests/target/allure-results/* joint-allure-results/


      # -------------------
      # 2) Ejecutar Cypress
      # -------------------
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Cypress dependencies
        working-directory: cipress/cypress-fotocasa-tests
        run: npm install

      - name: Run Cypress tests
        working-directory: cipress/cypress-fotocasa-tests
        run: npx cypress run

      - name: Copy Cypress Allure results
        run: cp -r cipress/cypress-fotocasa-tests/allure-results/* joint-allure-results/


      # -------------------
      # 3) Generar Allure Report unificado
      # -------------------
      - name: Generate Allure HTML report
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: joint-allure-results
          gh_pages: true
          publish_branch: gh-pages
          publish_dir: ./allure-report
